package pe.edu.unsch.entities;
// Generated 05/07/2019 01:46:48 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargaacademica generated by hbm2java
 */
@Entity
@Table(name = "cargaacademica", catalog = "cargabd")
public class Cargaacademica implements java.io.Serializable {

	private int idCarga;
	private int numeroHorasSemanales;
	private Set<Docente> docentes = new HashSet<Docente>(0);

	public Cargaacademica() {
	}

	public Cargaacademica(int idCarga, int numeroHorasSemanales) {
		this.idCarga = idCarga;
		this.numeroHorasSemanales = numeroHorasSemanales;
	}

	public Cargaacademica(int idCarga, int numeroHorasSemanales, Set<Docente> docentes) {
		this.idCarga = idCarga;
		this.numeroHorasSemanales = numeroHorasSemanales;
		this.docentes = docentes;
	}

	@Id

	@Column(name = "idCarga", unique = true, nullable = false, length = 8)
	public int getIdCarga() {
		return this.idCarga;
	}

	public void setIdCarga(int idCarga) {
		this.idCarga = idCarga;
	}
	
	@Column(name = "numeroHorasSemanales", nullable = false, length = 11)
	public int getNumeroHorasSemanales() {
		return this.numeroHorasSemanales;
	}

	public void setNumeroHorasSemanales(int numeroHorasSemanales) {
		this.numeroHorasSemanales = numeroHorasSemanales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargaacademica")
	public Set<Docente> getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set<Docente> docentes) {
		this.docentes = docentes;
	}

}
