package pe.edu.unsch.entities;
// Generated 05/07/2019 01:46:48 PM by Hibernate Tools 5.3.0.Beta2

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "cargabd")
public class Docente implements java.io.Serializable {

	private int idDocente;
	private Cargaacademica cargaacademica;
	private Semenstreacademico semenstreacademico;
	private String nombre;
	private String apellido;

	public Docente() {
	}

	public Docente(int idDocente, Cargaacademica cargaacademica, Semenstreacademico semenstreacademico, String nombre,
			String apellido) {
		this.idDocente = idDocente;
		this.cargaacademica = cargaacademica;
		this.semenstreacademico = semenstreacademico;
		this.nombre = nombre;
		this.apellido = apellido;
	}

	@Id

	@Column(name = "idDocente", unique = true, nullable = false, length = 8)
	public int getIdDocente() {
		return this.idDocente;
	}

	
	public void setIdDocente(int idDocente) {
		this.idDocente = idDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCarga", unique = true, nullable = false)
	public Cargaacademica getCargaacademica() {
		return this.cargaacademica;
	}

	public void setCargaacademica(Cargaacademica cargaacademica) {
		this.cargaacademica = cargaacademica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSemestre", unique = true, nullable = false)
	public Semenstreacademico getSemenstreacademico() {
		return this.semenstreacademico;
	}

	public void setSemenstreacademico(Semenstreacademico semenstreacademico) {
		this.semenstreacademico = semenstreacademico;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", nullable = false, length = 50)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

}
