package pe.edu.unsch.entities;
// Generated 05/07/2019 01:46:48 PM by Hibernate Tools 5.3.0.Beta2

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semenstreacademico generated by hbm2java
 */
@Entity
@Table(name = "semenstreacademico", catalog = "cargabd")
public class Semenstreacademico implements java.io.Serializable {

	private int idSemestre;
	private String semestre;
	private Set<Docente> docentes = new HashSet<Docente>(0);

	public Semenstreacademico() {
	}

	public Semenstreacademico(int idSemestre, String semestre) {
		this.idSemestre = idSemestre;
		this.semestre = semestre;
	}

	public Semenstreacademico(int idSemestre, String semestre,  Set<Docente> docentes ) {
		this.idSemestre = idSemestre;
		this.semestre = semestre;
		this.docentes = docentes;
	}

	@Id
	@Column(name = "idSemestre", unique = true, nullable = false, length = 8)
	public int getIdSemestre() {
		return this.idSemestre;
	}

	public void setIdSemestre(int idSemestre) {
		this.idSemestre = idSemestre;
	}

	@Column(name = "semestre", nullable = false, length = 50)
	public String getSemestre() {
		return this.semestre;
	}

	public void setSemestre(String semestre) {
		this.semestre = semestre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semenstreacademico")
	public  Set<Docente> getDocentes() {
		return this.docentes;
	}

	public void setDocentes( Set<Docente> docentes ) {
		this.docentes = docentes;
	}

}
